### ISSUE TITLE
No documentation on how this can be installed

### ISSUE THREAD

**Issue by daaain** [jasisk/slack-emoji-randomizer#1]
I promise I had a good look in Slack's documentation, but still can't see how do you install this.

Assuming from the fact that you mention how to enable dev tools, maybe it's a command which needs to be executed on the console?

Please add at least a link to some guidance in the README to help get people started (on their journey hacking Slack UI)! :)

**Comment by tylorr** [comment]
I would also love to know how this is installed

**Comment by jasisk** [comment]
Hey @tylorr and @daaain. Wasn't getting notified on this issue for some reason. Regardless, @jcnesci emailed me about this which prompted me to get this working for the latest slack client (1.1.8 as of today).

Installing this isn't the most straight forward since this whole thing is a hack, however here's how it's done:

In any chat room, send the following slash command by typing it into the chat input (like you would any other comment):

```
/macgap.app.enableDeveloperTools()
```

If done correctly, nothing will show up in the chat room and the input box will clear out.

At this point, you should be able to right-click anywhere in Slack and see a context menu with `Inspect Element` at the bottom. Click on that and the webkit dev tools will open up.

In the dev tools, click on the button across the top menu that reads, "Console". Once in there, you'll see a bar with a blue `>` at the very bottom of the window. Copy the contents of [`build/slack-emoji-randomizer.js`](https://raw.githubusercontent.com/jasisk/slack-emoji-randomizer/23a23a73861ff0e0fef853e01890d5c79ca658fe/build/slack-emoji-randomizer.js) and paste them into that little bar at the bottom of the window. Hit enter and, if all goes as planned, you should now see a new button in the slack window next to the search box. It will look like this:
![screen shot 2015-12-14 at 2 41 16 pm](https://cloud.githubusercontent.com/assets/62923/11791801/c6b64750-a270-11e5-8a72-448a510372e5.png)

A gray background (like in the screenshot above) means the emoji replacer is enabled. White means it's disabled.

At that point, any emoji you send to any channel in that slack team will be automatically randomized after a couple of seconds.

Note that this is not a persistent thing. If you restart the slack client, you'll have to go through this process again. Additionally, each Slack team uses it's own browser context so you'll have to do this for each team you want your emoji randomized.

Happy emoji-replacing!

**Comment by jcnesci** [comment]
Wow, this is some seriously awesome hacking! I love the deviousness of it... :)
Thanks for taking the time to update it and give us some guidance.
Happy Sl(h)acking everybody,

**Comment by daaain** [comment]
This is brilliant, thanks a lot @jasisk!

**Comment by jasisk** [comment]
Closing this out but if any of you need additional help, just continue the conversation. :grinning:
